#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

initramfs_test() {
	if [ -n "$INITRAMFS" ]; then
		boot_run_hook initramfs
		preinit_ip_deconfig
		break
	fi
}

# 给钩子preinit_main_hook注册函数initramfs_test
boot_hook_add preinit_main initramfs_test
