#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

# commands for emitting messages to network in failsafe mode

indicate_failsafe_led () {
	set_state failsafe
}

indicate_failsafe() {
	echo "- failsafe -"
	preinit_net_echo "Entering Failsafe!\n"
	indicate_failsafe_led
}

# 给钩子failsafe_hook注册函数indicate_failsafe
boot_hook_add failsafe indicate_failsafe
