#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

indicate_regular_preinit() {
	preinit_net_echo "Continuing with Regular Preinit\n"
	set_state preinit_regular
}

# 给钩子preinit_main_hook注册函数indicate_regular_preinit
boot_hook_add preinit_main indicate_regular_preinit
